Store owners in PDA
SvarogGuild/multisig pull request #1
Opened 2022-06-01 08:37 UTC by drmick

2022-06-01 10:18 UTC, 0nkery requested changes

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +use crate::ErrorCode::InvalidOwner;
Лишнее что-то, видимо.

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +    pub fn space_required() -> u64 {
Тут лучше сразу сделать `usize`.

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +            owners_amount: args.owners.len() as u64,
Не надо дублировать `args.owners`, если все есть в `remaining_accounts`.

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +            .proposer
Лучше `require!` использовать.

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +            Err(InvalidOwner)?
Тут тоже `require!`.

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +            return Err(ErrorCode::AlreadySigned.into());
И тут.

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
>          owners: Vec<Pubkey>,
Это лучше убрать, а остальное объединить в какую-то структурку.

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +                multisig_owner_data
Эту часть надо вынести в функцию или объект -- повторяется.

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +                **multisig_signer.lamports.borrow_mut() = dest_starting_lamports
Есть трейт `AccountClose`, который делает примерно то же самое.

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +    #[account(mut,
rustfmt :)

2022-06-01 10:18 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +    pub signers: Vec<u64>,
Поменяй тут на док-комменты, пжл.

2022-06-01 10:18 UTC, 0nkery commented on tests/multisig.js
> +    anchor.setProvider(anchor.Provider.env());
Сломались отступы? Нужно 2.

2022-06-01 10:18 UTC, 0nkery commented on tests/multisig.js
> +                {
Добавь еще запросы поиска владельцев по мультисигу и мультисигов по владельцу.

2022-06-02 06:48 UTC, drmick commented on programs/multisig/src/lib.rs
>          owners: Vec<Pubkey>,
если убрать owners не получится сформировать seeds

2022-06-02 17:36 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +                let multisig_owner: Account<'info, MultisigOwner> =
Тут проще сразу распарсить -- если не удалось, это значит, что нужно создать `MultisigOwner`. Короче, нужно убрать тот if сверху.

2022-06-02 17:36 UTC, 0nkery commented on programs/multisig/src/lib.rs
> +        if !ctx.remaining_accounts.is_empty() {
Это лучше в `require!` и проверять сразу.

2022-06-02 17:36 UTC, 0nkery commented on tests/multisig.js
> +    assert.ok(multisigAccount.ownersAmount.eq(new anchor.BN(5)));
```suggestion
    assert.ok(multisigAccount.ownersAmount.eqn(5));
```

2022-06-02 17:36 UTC, 0nkery commented on tests/multisig.js
> +    let updateOwnersAccounts = [
Попробуй тут все-таки список аккаунтов построить через `program.instruction`.

2022-06-02 18:07 UTC, drmick commented on programs/multisig/src/lib.rs
> +        if !ctx.remaining_accounts.is_empty() {
Список может быть пустым когда просто threshold будут менять без изменения владельцев, поэтому required не совсем подходит

2022-06-03 09:20 UTC, merged